version: "3.8"

services:
  # fastapi:
  #   build: .
  #   container_name: backend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P@ssword
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
